### ISSUE TITLE
empty assay after using prepareCellData()

### ISSUE THREAD

**Issue by msuffiot** [MarioniLab/cydar#1]
Hi,

I was trying to use cydar package in order to detect differences in populations abundance in mass cytometry data between time 0 and time 1 (after vaccination).
When I apply `prepareCellData` function to my transformed and normalized data in `ncdf` object, I get an empty assay 

```
 int[0 , 1:12] 
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr [1:12] "sample1v1.fcs" "sample1v2.fcs" "sample2v1.fcs" "sample2v2.fcs" ...
```

without getting errors or warnings..

How is this possible? Could someone help me? 

ps. I have quite a lot of cells events.. so just for testing I exported fcs for a single populations including about 200'000 cells

thank you very much in advance
best regards,
Madeleine

**Comment by LTLA** [comment]
Well, you need to `countCells` in order to get counts. The assays refer to the cell counts for hyperspheres, not the expression values for individual events.

**Comment by msuffiot** [comment]
Yes I see, but the input for `countCells` is the output of `prepareCellData` according to your examples.
If the ouput is of prepareCellData is empty, there is no chance to get results from countCells, right ?

**Comment by LTLA** [comment]
`countCells` will fill it up, just try some of the examples.
