### ISSUE TITLE
medIntensities for unused markers not sample-specific

### ISSUE THREAD

**Issue by ACRichard** [MarioniLab/cydar#3]
It would be helpful to be able to extract the hypersphere-specific (but not sample-specific) median intensities of markers that aren't used for hypersphere construction.  The current implementation of medIntensities currently separates by sample as well as hypersphere. Would it be possible to make this an optional argument for medIntensities?

**Comment by LTLA** [comment]
This is now available in 1.11.3 (installable either from here or from Bioc-devel in a few day's time). Calculation of median intensities for unused markers is now automatically performed as part of the usual `countCells()` and they can be extracted simply with `intensities(x, mode="unused")`.

Note that the medians are inversely weighted by the number of cells of each sample, just like the values returned by `intensities()` for the used markers. As a reminder, this ensures that samples with many cells do not dominate the calculation of the per-hypersphere median for each marker.
